import type { Metadata } from "next";
import "./globals.css";
import "@fontsource/rajdhani";
import Header from "@/components/header";
import {Footer} from "@/components/footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es" className="font-rajdhani">
      <body className="antialiased flex flex-col h-screen overflow-hidden">
         <Header></Header>
         <div className="flex-1 overflow-hidden">{children}</div>
         <Footer></Footer>
      </body>
    </html>
  );
}